### ISSUE TITLE
Stuff's broke tell me more

### ISSUE THREAD

**Issue by Graph-X** [Graph-X/davscan#1]
Since some people are finding this project useful enough to want to fork and/or star it.  First let me say... 
I am so sorry!  

Now that that's over with, I guess I have to actually work on and maintain this stuff.  I did limited testing on a known vulnerable server in controlled conditions so what I need from whoever is willing to do it.  Start testing this thing and let me know where I fucked up.  I have not gone through every permutation of options with this thing so there's a lot that I don't know.  If you find that I royally screwed the pooch on something, let me know and I'll fix it or ignore you until my feelings aren't hurt and I've stopped crying.  

Thanks!

-Graph-X

**Comment by dragoangel** [comment]
Hi, i test on WebDAV that over https, maybe I do something wrong. Or maybe no.
su chmod +x *.py
./davscan.py -H myIP -p 443 -o webdav-test.txt

```
[*]===========================================================[*]
[*]           Davscan v0.1                [*]
[*]            Written by Graph-X             [*]
[*]       e-mail: graphx@sigaint.org              [*]
[*]                twitter: @graphx               [*]
[*]===========================================================[*]
```

Traceback (most recent call last):
  File "./davscan.py", line 259, in <module>
    main()
  File "./davscan.py", line 131, in main
    f = fingerprinter.fingerprint(url,msf,dos) 
  File "/home/dalekseev/Desktop/davscan-master/fingerprinter.py", line 39, in fingerprint
    r = s.options(u)  
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 477, in options
    return self.request('OPTIONS', url, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='myIP', port=443): Max retries exceeded with url: / (Caused by <class 'httplib.BadStatusLine'>: '')

**Comment by Graph-X** [comment]
First thank you for speaking up. Second, I can reproduce the issue and I believe I know where the problem is so expect a fix sometime soon (US holidays prevent me from hacking away at this issue with attention span greater than a squirrel).   Third, your first initial last name spell Dalek Seev.  You should start and end all your communications from now on with "Exterminate!"

-Graph-X

**Comment by Graph-X** [comment]
Well, it only took me about a month to get to it, but I think I've fixed the SSL issues you were having.  Let me know if it's working or if I fucked up and it's hosed even worse now.  

-Graph-X

**Comment by dragoangel** [comment]
Sorry for big delay, not logging to GitHub. Not it not launching at all.

Traceback (most recent call last):
  File "./davscan.py", line 54, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4

Thanks for reply
-DRago_Angel

**Comment by Graph-X** [comment]
you need to install beautiful soup 4.  Sorry, I didn't realize that bs4 wasn't a part of the base python install.  "pip install bs4" should do the trick for you.

**Comment by Graph-X** [comment]
So either you forgot how to login to github (I do that too), installing bs4 worked and you didn't tell me it worked cause I'm a nobody halfway around the world from you, or it didn't work, you don't want to tell me for fear of hurting my feelings and have decided to quietly look elsewhere for a suitable solution to your problem which does not include my failed attempt at providing something other than toilet humor and rampant incompetence.  Regardless, I'm gonna close this issue out.
